FROM ubuntu:22.04

RUN apt update
RUN apt install -y build-essential
RUN apt install -y libpcre3 libpcre3-dev libssl-dev openssl
RUN apt install -y wget vim xz-utils
RUN apt install -y libc6-dev
RUN apt clean

WORKDIR /opt/src
RUN wget https://nim-lang.org/download/nim-1.6.12-linux_x64.tar.xz
RUN tar -xf nim-1.6.12-linux_x64.tar.xz 
RUN cd nim-1.6.12 && sh install.sh /usr/bin && bin/nim c koch && ./koch boot -d:release && ./koch tools

