FROM ubuntu:22.04

RUN apt update
RUN apt install -y build-essential
RUN apt install -y libpcre3 libpcre3-dev libssl-dev openssl
RUN apt install -y wget vim xz-utils
RUN apt install -y libc6-dev
RUN apt clean

WORKDIR /opt/src
RUN wget https://nim-lang.org/download/nim-1.6.12-linux_x64.tar.xz
RUN tar -xf nim-1.6.12-linux_x64.tar.xz 
RUN cd nim-1.6.12 && sh install.sh /usr/bin && bin/nim c koch && ./koch boot -d:release && ./koch tools
RUN cp /opt/src/nim-1.6.12/bin/* /usr/bin
RUN apt install -y git
RUN git clone https://github.com/PMunch/nimcr && cd nimcr && nim c -d:release nimcr.nim && mv nimcr /usr/bin
RUN mkdir /opt/src/nimble-packages
RUN HOME="/opt/src/nimble-packages" && nimble install -y glob
RUN HOME="/opt/src/nimble-packages" && nimble install -y https://github.com/reslp/nimbio
ENV NIMBLE_DIR=/opt/src/nimble-packages

WORKDIR /data

