FROM rocker/tidyverse:4.6.1

RUN apt update && apt install -y wget git

RUN wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
RUN bash Miniforge3.sh -b -p "/opt/conda"
ENV PATH="/opt/conda/bin:${PATH}"
RUN mamba install -c bioconda orthofinder=2.5.5

RUN apt install -y default-jdk
RUN cd /opt/ && git clone https://github.com/wyp1125/MCScanX && cd MCScanX && make
ENV PATH="/opt/MCScanX:${PATH}"

RUN install2.r -e remotes
#RUN R -q -e 'pak::pkg_install("jtlovell/GENESPACE")'
RUN R -q -e 'devtools::install_github("jtlovell/GENESPACE")'

RUN install2.r -e BiocManager
RUN R -q -e 'BiocManager::install(c("Biostrings", "rtracklayer"))'

RUN apt install -y libglpk-dev # the next line fails silently without this dependency
RUN R -q -e 'remotes::install_github("jtlovell/GENESPACE@dcb663b")'

CMD ["R"]
