FROM ubuntu:20.04

RUN apt-get update && apt-get install -y build-essential wget
WORKDIR /software
RUN wget https://github.com/hahnlab/CAFE5/releases/download/v5.1/CAFE5-5.1.0.tar.gz && tar xvfz CAFE5-5.1.0.tar.gz
RUN cd CAFE5 && ./configure && make && cp bin/cafe5 /usr/local/bin/cafe

WORKDIR /data
CMD ["cafe"]
