FROM nimlang/nim:2.0.8-ubuntu-regular

RUN apt update

WORKDIR /opt/src
RUN apt-get install -y git
RUN git clone https://github.com/PMunch/nimcr && cd nimcr && nim c -d:release nimcr.nim && mv nimcr /usr/bin
RUN mkdir /opt/src/nimble-packages
ENV NIMBLE_DIR=/opt/src/nimble-packages
RUN nimble install -y glob clapfn ggplotnim nimx
RUN nimble install -y https://github.com/reslp/nimbio  
RUN apt install -y curl

WORKDIR /data

