FROM ubuntu:24.04

RUN apt update && apt install -y build-essential
RUN apt install -y  wget

WORKDIR /opt/

RUN wget https://catchenlab.life.illinois.edu/stacks/source/stacks-2.68.tar.gz && tar xvfz stacks-2.68.tar.gz

RUN apt install -y zlib1g-dev pkg-config
RUN cd stacks-2.68 && ./configure && make && make install

