FROM continuumio/miniconda3:24.11.1-0
MAINTAINER <philipp.resl@uni-graz.at>

ENV PATH /opt/conda/bin:$PATH

RUN conda config --append channels bioconda && \
	conda config --append channels conda-forge && \
	conda config --append channels anaconda && \
	conda install -y -c conda-forge mamba=2.0.5 && \
	conda clean -a -y

CMD ["mamba"]
