FROM ubuntu:22.04

#RUN mamba install -c anaconda tk=8.6.12
#RUN mamba install -y -c conda-forge binutils
#RUN conda run -n base python -m pip install pyinstaller==6.1
#RUN mamba install -y -c anaconda pyinstaller=5.6.2
RUN apt update 
RUN apt install -y python3 python3-dev python3-pip
RUN pip install pyinstaller==6.1


WORKDIR /data

CMD ["pyinstaller"]
