FROM ubuntu:24.04

RUN apt update && apt install -y python3 build-essential python3-pip git && apt clean
WORKDIR /etc/software
RUN git clone https://github.com/plant720/Easy353.git && cd Easy353 && git checkout v2.0.2
RUN apt install -y python3-biopython python3-psutil python3-requests python3-bs4
RUN chmod +x /etc/software/Easy353/build_database.py && chmod +x /etc/software/Easy353/easy353.py
ENV PATH="$PATH:/etc/software/Easy353/"
RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /data

CMD ["easy353.py"]
