FROM reslp/mamba:0.15.3
#SHELL ["/bin/bash", "-c"]

#RUN . /opt/conda/etc/profile.d/conda.sh
#RUN source $HOME/.bashrc
#RUN conda config --set notify_outdated_conda false
RUN mamba install -y -c bioconda spades=3.15.3

WORKDIR /data

CMD ["spades.py", "-h"]

